version: "3.7"

services:
  tools:
    build:
      context: .
    volumes:
      - .:/code
    command: ["python --version"]
  tests:
    build:
      context: .
      target: tests
    volumes:
    - .:/code
    command: ["pytest"]
