[build-system]
requires = ["setuptools>=51.0.0", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "deafrica/_version.py"

[tool.black]
exclude = "deafrica/platform/warn_unused_sandbox_volumes.py"

[tool.isort]
profile = "black"