# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.0.14.dev32+g77bcddb.d20211005'
version_tuple = (0, 0, 14, 'dev32', 'g77bcddb.d20211005')
